name: mala-cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.3.1
  - alembic=1.9.1
  - ase=3.22.1
  - async-timeout=4.0.2
  - attrs=22.2.0
  - autopage=0.5.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blinker=1.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cachetools=5.2.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cliff=3.10.1
  - cmaes=0.9.0
  - cmd2=2.4.2
  - colorama=0.4.6
  - colorlog=6.7.0
  - contourpy=1.0.6
  - cryptography=38.0.4
  - cycler=0.11.0
  - flask=2.2.2
  - fonttools=4.38.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - google-auth=2.15.0
  - google-auth-oauthlib=0.4.6
  - greenlet=2.0.1
  - grpcio=1.51.1
  - icu=70.1
  - idna=3.4
  - importlib-metadata=4.11.4
  - importlib_resources=5.10.1
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - lcms2=2.14
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libabseil=20220623.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libdeflate=1.14
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgrpc=1.51.1
  - libhwloc=2.8.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.5.0
  - libuuid=2.32.1
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=15.0.6
  - mako=1.2.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib-base=3.6.2
  - mkl=2022.2.1
  - mpmath=1.2.1
  - multidict=6.0.2
  - munkres=1.1.4
  - ncurses=6.3
  - ninja=1.11.0
  - numpy=1.24.0
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openssl=3.0.7
  - optuna=3.0.5
  - packaging=22.0
  - pandas=1.5.2
  - pbr=5.11.0
  - pillow=9.2.0
  - pip=22.3.1
  - prettytable=3.5.0
  - protobuf=4.21.12
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyjwt=2.6.0
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pyperclip=1.8.2
  - pysocks=1.7.1
  - python=3.8.15
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.13.0
  - pytorch-cpu=1.13.0
  - pytz=2022.7
  - pyu2f=0.1.5
  - pyyaml=6.0
  - re2=2022.06.01
  - readline=8.1.2
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scipy=1.8.1
  - scikit-spatial=6.8.1
  - setuptools=59.8.0
  - six=1.16.0
  - sleef=3.5.1
  - sqlalchemy=1.4.45
  - stevedore=4.1.1
  - tbb=2021.7.0
  - tensorboard=2.11.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tk=8.6.12
  - tqdm=4.64.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - unicodedata2=15.0.0
  - urllib3=1.26.13
  - wcwidth=0.2.5
  - werkzeug=2.2.2
  - wheel=0.38.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.8.1
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
