name: mala-cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6, <3.9
  - pip
  - numpy
  - scipy
  - optuna
  - pandas
  - ase
  - pytorch-cpu
  - mpmath
  - tensorboard
  - scikit-spatial
